# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 831d91c6ef34d99a19014ede53496ee185a227d298f5fb023dfc289eb359bc303a3e09fa8a1877193ed1afb5654d6b1bbbf00d102ecd9e794e9f18e6ef1c5cc4

test:
  secret_key_base: b9cd66f1805e48569d10cde920a96feaad925cf06ebd741a6b5ab1d700362df094751ffd12a8f97befe6bf9b295e50ef444eebfd17bde4658f14abe1f099aefe

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
